<h2>Try with resources</h2>
<div class="step-text">
<p>We have mentioned that <strong><a class="theory-lookup" href="/learn/step/9723" rel="noopener noreferrer nofollow" target="_blank" title="In Java, an Input Stream is a component of the Java API that allows reading data from a source, such as a console, standard input, a file, a string, or even a network connection. | Input Streams can be classified into two types: byte and character. Character Input Streams, which are designed for reading text, encode bytes to characters immediately, making them suitable for text-based data. On the other hand, Byte Input Streams are used for reading raw bytes of data, such as audio, video, or zip files.">input streams</a></strong> should be closed after they were used. Let's discuss what happens when you're working with outside resources: how closing can be performed and why it is important.</p>
<h5 id="why-close">Why close?</h5>
<p>When an<strong> </strong>input stream is created, the JVM notifies the OS about its intention to work with a file. If the JVM process has enough permissions and everything is fine, the OS returns a <strong><a class="theory-lookup not-relevant" href="/learn/step/9734" rel="noopener noreferrer nofollow" target="_blank" title="In Java, a file descriptor is a special indicator used by a process to access a file. | When an input stream is created, the Java Virtual Machine (JVM) notifies the operating system (O.S.) about its intention to work with a file. If the JVM process has sufficient permission and everything is fine, the O.S. returns a file descriptor, which is then used by the JVM to read or write data from/to the file. It is important to release the file descriptor once the job is done, so it can be reused, as the number of file descriptors is limited. This can be done by notifying the O.S. that the job is done and the file descriptor can be released.">file descriptor</a></strong> â€” a special indicator used by a process to access the file. The problem is that the number of file descriptors is limited. This is a reason why it is important to notify the OS that the job is done and the file descriptor that is held can be released for further reusing. In previous examples, we invoked the method <code class="language-java">close</code> for this purpose. Once it is called, the JVM releases all system resources associated with the stream.</p>
<h5 id="pitfalls">Pitfalls</h5>
<p>Resource releasing works if the JVM calls the <code class="language-java">close</code> method, but it is possible that the method will not be called at all.</p>
<p>Look at the example:</p>
<pre><code class="language-java">Reader reader = new FileReader("file.txt");
// code which may throw an exception
reader.close();</code></pre>
<p>Suppose something goes wrong before the <code class="language-java">close</code> invocation and an exception is thrown. It leads to a situation in which the method will never be called and system resources won't be released. It is possible to solve the problem by using the <strong>try-catch-finally</strong> construction:</p>
<pre><code class="language-java">Reader reader = null;

try {
    reader = new FileReader("file.txt");
    // code which may throw an exception
} finally {
    reader.close();
}</code></pre>
<p>In this and the following examples, we assume that <code class="language-java">file.txt</code> exists and do not check the instance of <code class="language-java">Reader</code> for <code class="language-java">null</code> in the <code class="language-java">finally</code> block. It is done to keep the code snippet as simple as possible, but it is not safe in the case of a real application.</p>
<p>Thrown exceptions cannot affect the invocation of the <code class="language-java">close</code> method now.</p>
<p>Unfortunately, this solution still has some problems. That is, the <code class="language-java">close</code> method can potentially raise exceptions itself. Suppose, now there are two exceptions: the first was raised inside the <code class="language-java">try</code><em> </em>section, and the second was thrown by the <code class="language-java">finally</code><em> </em>section. It leads to the loss of the first exception. Let's see why this happens:</p>
<pre><code class="language-java">void readFile() throws IOException {
    Reader reader = null;
    try {
        reader = new FileReader("file.txt");
        throw new RuntimeException("Exception1");
    } finally {
        reader.close(); // throws new RuntimeException("Exception2")
    }
}</code></pre>
<p>First, the <code class="language-java">try</code><em> </em>block throws an exception. As we know, the <code class="language-java">finally</code> block is invoked anyway. In our example, now the <code class="language-java">close</code> method throws an exception. When two exceptions occur, which one is thrown outside the method? It will be the last one: <code class="language-java">Exception2</code> in our case. It means we will never know that the <code class="language-java">try</code><em> </em>block raised an exception at all.</p>
<p>Let's try to reason and fix this. Ok, we don't want to lose the first exception, so we upgrade the code a little bit and handle <code class="language-java">Exception2</code> right after it was thrown:</p>
<pre><code class="language-java">void readFile() throws IOException {
    Reader reader = null;
    try {
        reader = new FileReader("file.txt");
        throw new RuntimeException("Exception1");
    } finally {
        try {
            reader.close(); // throws new RuntimeException("Exception2")
        } catch (Exception e) {
            // handle the Exception2
        }
    }
}</code></pre>
<p>Now, the piece of code throws <code class="language-java">Exception1</code> outside. It may be correct, but we still do not save information on both exceptions, and sometimes we don't want to lose it. So now, let's see how we can handle this situation nicely.</p>
<h5 id="solution">Solution</h5>
<p>A simple and reliable way called <strong>try-with-resources</strong> was introduced in Java 7.</p>
<pre><code class="language-java">try (Reader reader = new FileReader("file.txt")) {
    // some code
}</code></pre>
<p>This construction has two parts enclosed by round and curly brackets. Round brackets contain statements that create an input stream instance. It is possible to create several objects as well. The code below is also fine:</p>
<pre><code class="language-java">try (Reader reader1 = new FileReader("file1.txt");
     Reader reader2 = new FileReader("file2.txt")) {
    // some code
}</code></pre>
<p>The second part just contains some code for dealing with the object that was created in the first part.</p>
<p>As you see, there are no explicit calls of the <code class="language-java">close</code> method at all. It is implicitly invoked for all objects declared in the first part. The construction guarantees closing all resources in a proper way.</p>
<p>Since Java 9, you may initialize an input stream outside the construction and then declare it in round brackets:</p>
<pre><code class="language-java">Reader reader = new FileReader("file.txt");
try (reader) {
    // some code
}</code></pre>
<p></p>
<div class="alert alert-primary">Surely we do our best to write error-free programs. However, it is difficult to foresee all possible problems. The best practice is to wrap any code dealing with system resources by the try-with-resources construction</div>
<p></p>
<p>You may also use<strong> </strong>try-with-resources as a part of try-catch-finally like this:</p>
<pre><code class="language-java">try (Reader reader = new FileReader("file.txt")) {
    // some code
} catch(IOException e) {
    ...
} finally {
    ...
}</code></pre>
<p> Now let's go back to our two-exceptions case. If both the <code class="language-java">try</code> block and <code class="language-java">close</code> method throw exceptions <code class="language-java">Exception1</code> and <code class="language-java">Exception2</code>:</p>
<pre><code class="language-java">void readFile() throws IOException {
    try (Reader reader = new FileReader("file.txt")) {
        throw new RuntimeException("Exception1");
    }
}</code></pre>
<p>the method throws the resulting exception, which comprises information on both exceptions. It looks like this:</p>
<pre><code class="language-java">Exception in thread "main" java.lang.RuntimeException: Exception1
	at ...
	Suppressed: java.lang.RuntimeException: Exception2
		at ...</code></pre>
<h5 id="closeable-resources">Closeable resources</h5>
<p>We have dealt with a file input stream to demonstrate how try-with-resources is used. However, not only resources based on files should be released. Closing is crucial for other outside sources like web or database connections. Classes that handle them have a  <code class="language-java">close</code> method and therefore can be wrapped by the try-with-resources <a class="theory-lookup not-relevant" href="/learn/step/9734" rel="noopener noreferrer nofollow" target="_blank" title="In Java, a statement is a unit of code that performs a specific action. | It can be a standalone instruction or a part of a larger block of code. A statement can take various forms, such as assignment statements, object creation statements, method invocation statements, or control flow statements. Control flow statements, such as if-else statements or switch statements, allow for decision-making and conditional execution of code based on certain conditions. A statement's execution order is determined by the program's control flow, which can be affected by blocks, loops, and other control structures.">statement</a>.</p>
<p>For example, let's consider <code class="language-java">java.util.Scanner</code>. Earlier we used <code class="language-java">Scanner</code> for <a class="theory-lookup not-relevant" href="/learn/step/9734" rel="noopener noreferrer nofollow" target="_blank" title="In Java, a read is a method used to obtain data from an input stream, such as a file or network connection. | These methods block the program from running until some input is available or the end of the stream is reached. For example, the `read()` method of the `InputStream` class reads a single byte of data from the input stream and returns it as an integer. The `read(byte[] b)` method reads up to a specified number of bytes of data from the input stream into an array and returns the number of bytes read. It is important to note that the `read()` method does not necessarily fill the entire array if data is not available.">reading</a> data from the standard input, but it can read data from a file as well. <code class="language-java">Scanner</code> has a <code class="language-java">close</code> method for releasing outside sources.</p>
<p>Let's consider an example of a program that reads two integers separated by a space from a file and prints them:</p>
<pre><code class="language-java">try (Scanner scanner = new Scanner(new File("file.txt"))) {
    int first = scanner.nextInt();
    int second = scanner.nextInt();
    System.out.println("arguments: " + first + " " + second);
}</code></pre>
<p>Suppose something went wrong and the file content is <code class="language-java">123 not_number</code>, where the second argument is a <code class="language-java">String</code>. It leads to a <code class="language-java">java.util.InputMismatchException</code> while parsing the second argument. Try-with-resources guarantees that file-related resources are released properly.</p>
<h5 id="conclusion">Conclusion</h5>
<p>Inappropriate resource handling may lead to serious problems. Resources associated with files, web, database, or other outside sources should be released after being used. Standard library classes dealing with outside sources have a <code class="language-java">close</code> method for that purpose. Sometimes releasing resources in a proper way may get complicated. To simplify the process, Java 7 introduced the try-with-resources construction that does all the work for you. Do not forget to use it when you're dealing with system resources.</p>
</div>
